### ISSUE TITLE
User story driven API design

### ISSUE THREAD

**Issue by timcappalli** [WICG/identity-credential#13]
During the discussions regarding the establishment of a W3C working group, several questions have emerged about integrating verifiable credentials, mdocs, and federated assertions into a unified interface and API surface. To better understand how users are likely to engage with these credentials, it may be useful to frame the discussion in terms of a user story or journey. Doing so could help us achieve greater alignment on this approach.

A mobile driver's license is a clear example of an identity credential that can serve as proof of age. However, there are also situations where a federated identity provider could offer verified age information through an OIDC ID token. Likewise, a request for proof of employment could be fulfilled by either a verifiable credential from a wallet or an assertion from LinkedIn via OIDC.

Developers typically rely on OIDC ID tokens as a familiar assertion format that enjoys broad industry support. In some cases, the trust established with the identity provider may be sufficient to satisfy verifiers. Additionally, the end user may already have a session established with the IdP and prefer not to retrieve a wallet-based credential from their phone. Alternatively, the user may be hesitant to directly share information from their driver's license with a verifier.

For this example, we can imagine a credential picker-style experience that assists the user in presenting the appropriate age or employment proof to the verifier, based on the user's level of comfort and the verifier's requirements.

**Comment by OR13** [comment]
I like user stories a lot, but I also find the JTBD framework helpful, https://www.youtube.com/watch?v=xQV7HVyAJjc&t=1976s

especially at mitigating the risks associated with fitting a technology to areas where it does not belong.

**Comment by dlongley** [comment]
+1 to the concept that there are different approaches and user needs here.

> especially at mitigating the risks associated with fitting a technology to areas where it does not belong.

For more along that line of thinking, there's a VC protocol discussion here around whether it is worth reusing primitives that have served one model well with a new model where they may not be a good fit:

https://mailarchive.ietf.org/arch/msg/oauth/r6HsZnMAVBYSvYraCsRYKinQUV0/

**Comment by timcappalli** [comment]
The current discussions have had user experience and privacy at the forefront. Nothing actionable with this issue, so closing.
