### ISSUE TITLE
Separating identity and authentication in the API shape

### ISSUE THREAD

**Issue by hober** [WICG/identity-credential#16]
Probably the most straightforward way would be to split something identity-specific off of the existing `navigator.credentials.get()`, which would then be used for non-identity stuff. `navigator.credentials.getIdentity()` maybe?

**Comment by hober** [comment]
Maybe this is a dup of #10?

**Comment by RByers** [comment]
Thanks Tess. I do think this is a dupe of #10, so I'll follow up there.
