### ISSUE TITLE
Start a regular meeting

### ISSUE THREAD

**Issue by RByers** [WICG/identity-credential#18]
Figure out time / attendees, etc. Will track details here.

**Comment by RByers** [comment]
@timcappalli to send out a doodle for picking times

**Comment by Sakurann** [comment]
conflicts to avoid:
- OIDF Digital Credentials Protocols WG (DCP WG) on thursdays that you can find on[ this calendar](https://openid.net/calendar/)
- W3C VC WG that are on tuesdays/wednesdays that you can find on [this calendar](https://www.w3.org/groups/wg/vc/calendar/). 
- regular IETF SD-JWT (selective disclosure for JWTs) calls (monday/tuesday 8am ish PST) 
(above calls are rotating... )
- ad hoc ISO mDL task force calls (usually 5am-8am PST wednesdays).

**Comment by timcappalli** [comment]
"A" call is North America friendly, every other week, starting the week of 9/25.
"B" call is Asia-Pacific friendly, every other week, starting the week of 10/2.

A call poll: https://doodle.com/meeting/participate/id/azX1Y4md
B call poll: https://doodle.com/meeting/participate/id/el7JEkrd

**Comment by timcappalli** [comment]
This info has also been added to the README in the repo.

📆 [ICS file (calendar items)](https://drive.google.com/file/d/1haMW6sSb9FFRY4p4XrcYeYhQ9cOiTYzm/view?usp=sharing)

* Asia\Pacific friendly time meeting B is every two weeks starting on 🔗 [2023-10-05 00:00 GMT](https://www.timeanddate.com/worldclock/converter.html?iso=20231005T000000&p1=240&p2=248&p3=776&p4=136&p5=tz_gmt&p6=43&p7=1203&p8=24&p9=75&p10=1241&p11=234)

* North America friendly time meeting A is every two weeks starting on 🔗 [2023-10-09 19:00 GMT](https://www.timeanddate.com/worldclock/converter.html?iso=20231009T190000&p1=240&p2=248&p3=776&p4=136&p5=tz_gmt&p6=43&p7=1203&p8=24&p9=75&p10=1241&p11=234)

**Comment by asr-enid** [comment]
FWIW - both of these slots are not workable for regular participation from interested parties from Europe (9pm, 2am)

**Comment by timcappalli** [comment]
@asr-enid and others. We're going to try a new poll for the A call. Please add your availability as soon as possible.

https://doodle.com/meeting/participate/id/e921KV8a

**Comment by RByers** [comment]
With the caveat that we're not actually meeting next Monday due to IIW (and Canadian Thanksgiving for me). But this will be the regular NA+EMEA-friendly slot every two weeks after that.

**Comment by timcappalli** [comment]
new meeting time picked based on doodle. all details in the repo readme: https://github.com/WICG/identity-credential/blob/main/README.md
