### ISSUE TITLE
[Planning] Internet Identity Workshop (IIW) - October 2023

### ISSUE THREAD

**Issue by timcappalli** [WICG/identity-credential#24]
Issue to help coordinate IIW sessions for next week.

/cc @samuelgoto

**Comment by samuelgoto** [comment]
Here are a few sessions that we figured it would be constructive to agitate, and some of the people that would be involved:


| Title      | Agitators | Agitators |
| ----------- | ----------- | ----------- |
| The Android API Proposal |  leecam      |  An introduction and overview of the architecture and design choices of Android’s IdentityCredential API. For example: credentials choosers vs wallet choosers, WASM matchers, format-independence, response encryption, sandboxing and privacy properties, UX design choices, etc, demos, Q&A, timelines, etc |
| The Browser API Proposal | goto |  An introduction and overview of the architecture of the Web’s IdentityCredential API (query languages, format-independence, cross device architecture, etc), demos (https://www.identitycredential.dev/),  Q&A, timelines, etc |
| The Browser API && ISO | davidz, gareth | An open discussion of how ISO thinks of the various Android and Web APIs |
| The Browser API && VCs | manu / kristina / orie? | An open discussion on how the Android/Chrome API could help the VC ecosystem (e.g. missing features, concerns, tec) |
| The Browser API && Wallets | spruce? | An open discussion on how the Android/Chrome API could help the Wallet ecosystem |
| The Browser API && Standards | tim | An open discussion around the relationship between the ICCG, the CCG, FedID CG, OIDF, IETF and ISO and how to engage across the various groups. How does the Browser API relate to OpenID4VP? CHAPI? DIDComm? |
| Open Design Question: Federated Identities, Digital Identities and Passkeys | federation (the OpenID / SAML folks?) and wallet experts (kristina? orie? manu?) | An open discussion around the relationship between federated and digital identities and how we expect things to play out, the development of FedCM, the Identity Credentials API and WebAuthn |
| Open Design Question: Query languages | Presentation Exchange Experts? | What should be the browser's API query language? should it be extensible? should it be presentation exchange? should it be format specific or format agnostic? Should it be opaque to the browser? |
| Open Design Question: Credential Selectors vs Wallet Selectors | leecam, kristina? | Which direction should we go? What are the trade-offs? |

Not super well thought out, but this is what occurs to me as things that would be interesting to get out of IIW.

WDYT?

**Comment by Sakurann** [comment]
wrt demo tables, IIW has demo hour during lunch on day 2. here is the list of demo tables as of now: https://iiw.idcommons.net/IIW_37_Speed_Demo_Hour

**Comment by samuelgoto** [comment]
> wrt demo tables, IIW has demo hour during lunch on day 2. here is the list of demo tables as of now: https://iiw.idcommons.net/IIW_37_Speed_Demo_Hour

Neat! Thanks for the advice! I think I got us the last slot!

**Comment by csuwildcat** [comment]
Can we shift the query portion to Day 2? I can't attend Day 3 😕

**Comment by msporny** [comment]
> Can we shift the query portion to Day 2? I can't attend Day 3 😕

Same issue here, I won't be at day 3. Perhaps we can level set in the morning on Monday, and then do the query portion on day 2 (morning / afternoon)?

**Comment by Sakurann** [comment]
Thanks! few comments:

On "credential selectors vs wallet selectors", would like to do it on end day 1 or in the beginning of day 2. The topic does require an understanding of the browser API and presentation protocols like OpenID4VP, so 101 sessions to those should happen first, but this topic could have impact on the design of things so would like to do it sooner rather than later.

Two sessions "The Browser API && VCs" and "The Browser API && ISO mdocs" could probably combined into "The Browser API and credential formats".

Curious why "The Android API Proposal" and "The Browser API Proposal" are proposed to be separate sessions? I might be wrong, but aren't they better understood when described together? 

A bit concerned with a description of `how does it compare to URI-schemes (mdoc:// and mdoc-openid4vp://) in 18013-7`. OID4VP does not mandate custom url schemes :) the topic sounds like "browser API and 18013-7".

**Comment by paulbastian** [comment]
To me "Credential Selectors vs Wallet Selectors" seems like the trend setting topic, so it makes most sense to do that at day1.

**Comment by samuelgoto** [comment]
> Curious why "The Android API Proposal" and "The Browser API Proposal" are proposed to be separate sessions? I might be wrong, but aren't they better understood when described together?

Yeah, we could combine these. There is a LOT of ground to cover here, so I was thinking that two separate sessions would be helpful allowing them more time, but I don't mind combining them and in case we overflow we can schedule more time.

Done.

**Comment by samuelgoto** [comment]
> Two sessions "The Browser API && VCs" and "The Browser API && ISO mdocs" could probably combined into "The Browser API and credential formats".

Done. I was a bit concerned that the people involved would rather have a dedicated time for their format, but I don't mind combining and having everybody be in the same room.

**Comment by samuelgoto** [comment]
I hear from @paulbastian 

> To me "Credential Selectors vs Wallet Selectors" seems like the trend setting topic, so it makes most sense to do that at day1.

and @Sakurann 

> On "credential selectors vs wallet selectors", would like to do it on end day 1 or in the beginning of day 2. The topic does require an understanding of the browser API and presentation protocols like OpenID4VP, so 101 sessions to those should happen first, but this topic could have impact on the design of things so would like to do it sooner rather than later.

Done. Moved this discussion to Day 1.

Day 1 is going to be heavy, with three full sessions, but I think that's manageable.

I think I addressed most of the comments here.

What do you all think of how the schedule is now?

**Comment by Sakurann** [comment]
Thanks Sam! just a note that there will be an OpenID4VC 101 session on day 1, which we should avoid having conflict with :)

**Comment by samuelgoto** [comment]
> Thanks Sam! just a note that there will be an OpenID4VC 101 session on day 1, which we should avoid having conflict with :)

Yeah, that's what I was worried to not overloading the days too much, since there are going to be a lot of parallel sessions that most of us would normally attend.

**Comment by samuelgoto** [comment]
Can we close this? IIW happened and we hosted most of these discussion in formal/informal sessions.

**Comment by msporny** [comment]
+1 to close, though it would be good to have a list of actions/outcomes from each meeting. I know, I know, none of us have the time to write that up ... don't know if people were taking IIW notes and we could use those as a bulleted list of each topic?

**Comment by timcappalli** [comment]
Closing after 2+ weeks.
