### ISSUE TITLE
[Discuss] Should multiple wallets be supported in the same ceremony?

### ISSUE THREAD

**Issue by timcappalli** [WICG/identity-credential#26]
> Surfaced as a core discussion topic on the first call ([2023-10-04](https://github.com/WICG/identity-credential/wiki/2023-10-04-Meeting-Notes)).

**Comment by npdoty** [comment]
I don't recall this one and can't interpret it from the notes. can someone remind me of the details of this question?

**Comment by timcappalli** [comment]
Discussed on the [2023-10-18 call](https://github.com/WICG/identity-credential/wiki/2023-10-18-Meeting-Notes#multiple-wallets): for incubation and MVP, the focus should be on supporting one presentation and wallet per ceremony
