### ISSUE TITLE
[Discuss] Common vocabulary/terminology

### ISSUE THREAD

**Issue by timcappalli** [WICG/identity-credential#28]
> Surfaced as a core discussion topic on the first call ([2023-10-04](https://github.com/WICG/identity-credential/wiki/2023-10-04-Meeting-Notes)).

Need for a common vocabulary / terminology for these discussions (e.g. encoding, formats, schemes, etc)

**Comment by samuelgoto** [comment]
Subtopic: is there a good name that can use to describe credentials independent of format? Something that can fit into this sencence: "W3C VCs and ISO mDocs are a type of _____". Can we converge on the term is used in OpenID, [Digital Credentials](https://openid.net/wg/digital-credentials-protocols/)?

**Comment by samuelgoto** [comment]
Here is an initial take on how I have been (personally, and likely, incorrectly) using the terms. 

Feel free to add your own (terms) and semantics:

https://docs.google.com/document/d/1ZYO1MpoFJ53AMDw6ALtbEVK_gRsBuHNC3IBh2Lbcv0w/edit

**Comment by timcappalli** [comment]
Added link to the terminology doc to the wiki (https://github.com/WICG/identity-credential/wiki). Closing issue.
