### ISSUE TITLE
Support for web-based wallets

### ISSUE THREAD

**Issue by msporny** [WICG/identity-credential#34]
One common use case that we've supported in the Credentials CG work, and CHAPI (Credential Handler API), for a while now is the ability to invoke web-based wallets to respond to a request. There is a lot of focus on high-assurance use cases these days (government-issued digital identity tied to hardware security keys on mobile phones and app attestations). This raises the bar for what a "digital wallet" is to a degree that is much higher than a number of other use cases in the VC ecosystem (education VCs, pseudonymous age-over assertions, pseudonymous digital coupons, etc.). It is also possible for a web-based wallet to deliver VCs that are signed by HSM-based keys. For these reasons, CHAPI supports the invocation of both web-based digital wallets and native digital wallets (as evidenced by multiple implementations in the latest JFF Plugfest 3).

Whatever this work ends up becoming, there needs to be a consideration for both web-based wallets and native wallets through the same interface.

**Comment by timcappalli** [comment]
merging into #33
