### ISSUE TITLE
[PROCESS] "pending close" should only be used after result of discussion is documented

### ISSUE THREAD

**Issue by msporny** [WICG/identity-credential#47]
There are a few issues that have been marked "pending close" without it being clear why they're being marked as such:

https://github.com/WICG/identity-credential/issues/32
https://github.com/WICG/identity-credential/issues/39
https://github.com/WICG/identity-credential/issues/43

This comes across as arbitrary closing of issues instead of what's probably happening, which is that the issue was discussed on a call and that resulted in some rough consensus on a conclusion like: "Rough consensus is to do X."

Please document why the issue is being closed with a simple conclusion before closing issues. A sentence or two will do in most cases.

**Comment by timcappalli** [comment]
> Please document why the issue is being closed with a simple conclusion before closing issues. A sentence or two will do in most cases.

That is the plan.

**Comment by marcoscaceres** [comment]
Closing as we are already doing this (I.e., we will state why an issue is closed or addressed)

**Comment by TallTed** [comment]
> Closing as we are already doing this (I.e., we will state why an issue is closed or addressed)

I find it difficult to understand or fully accept the above statement, while such resolution statements were not timely and/or are not easily found on the issues (#32 — resolution summary added two weeks after tag added; #39 — tag added with no resolution summary I can see; #43 — 11 comments after tag added!) cited at the opening of *this* issue (#47).

This issue appears to me to be being closed aspirationally, not operationally.
