### ISSUE TITLE
nonce missing in the Verifiable Credentials example

### ISSUE THREAD

**Issue by Sakurann** [WICG/identity-credential#6]
nonce should be mandatory to be included in the returned Verifiable Presentation and binds it to a transaction. (nonce might not be explicitly mentioned in the W3C vc-data-model, but it is because how to transport VCs is out of scope of that document). 
(I included nonce in the example in the Issue #5)

**Comment by samuelgoto** [comment]
Good point!

[Done](https://github.com/WICG/identity-credential/commit/ee4a3847117ab4299b456cf91aa8f12331aea391).
