### ISSUE TITLE
Is only MDocs response expected to be encrypted?

### ISSUE THREAD

**Issue by Sakurann** [WICG/identity-credential#8]
FedCM and VC examples do not contain `readerPublicKey`. Does that mean those responses are not expected to be encrypted? or in the case of FedCM, IdP is supposed to use publicKey of the RP it has obtained during pre-registration..?

**Comment by samuelgoto** [comment]
The expectation is that the browser doesn't introspect in an of the response types (neither for FedCM nor for VCs nor for mDocs).

Resolving, feel free to re-open if you feel that this isn't really what you were hoping for.
