### ISSUE TITLE
"type" missing in Verifiable Credentials

### ISSUE THREAD

**Issue by Sakurann** [WICG/identity-credential#9]
"type" (in certain Verifiable Credential formats) is used to identify syntax and semantics of the Claims in the Credential between the Wallet and the Verifier. It is missing from [Verifiable Credentials example](https://github.com/agl/identity-credential#verifiable-credentials), but is present in the Reconciliation example, so I assume the omission was not intentional.

**Comment by samuelgoto** [comment]
Ah yeah, totally unintentional. 

[Done](https://github.com/WICG/identity-credential/commit/2ff32cbae57fbeba9052f1a0736ca9cad5380b5a).

FWIW, do you have an example that you like best? What's the flagship use case for VCs?
